const fs = require('fs')

module.exports.es = {
    expoDescription: fs.readFileSync('./src/copies/partials/expoAliciaAyaneguiDescriptionEs.txt').toString('utf-8'),
    username: 'Nombre de usuario',
    message: 'Mensaje',
    startMessage: 'Bienvenido al chat. Mientras dure la transmisión en vivo, puedes preguntar o comentar lo que desees al artista o a los curadores.',
    image1: 'Pilares',
    image2: 'Peso amarillo',
    image3: 'Blancos',
    image4: 'Cinta azul',
    image5: 'Sombra roja',
    image6: 'Reflejo',
    image7: 'Paisaje',
    image8: 'Frío',
    image9: 'Hielo',
    image10: 'Neblina fría',
    image11: 'Uno',
    image12: 'Humo',
    image13: 'Algo en el piso (díptico)',
    image14: 'Desapariciones (díptico)',
    image15: 'Lodoso',
    image16: 'Humedad',
    image17: 'De cristal',
    image18: 'En el baño',
    image19: 'Sólo en sueños',
    material: 'Óleo sobre papel',
    material2: 'Óleo sobre lienzo',
}

module.exports.en = {
    expoDescription: fs.readFileSync('./src/copies/partials/expoAliciaAyaneguiDescriptionEn.txt').toString('utf-8'),
    username: 'User name',
    message: 'Message',
    startMessage: 'Welcome to the chat. Meanwhile the transmission is online you can make any questions or comments to artist or curators.',
    image1: 'Pillars',
    image2: 'Yellow weight',
    image3: 'White',
    image4: 'Blue ribbon',
    image5: 'Red shadow',
    image6: 'Reflect',
    image7: 'Landscape',
    image8: 'Cold',
    image9: 'Ice',
    image10: 'Cold fog',
    image11: 'One',
    image12: 'Smoke',
    image13: 'Something on the floor (diptych)',
    image14: 'Disappearances (diptych)',
    image15: 'Muddy',
    image16: 'Dampness',
    image17: 'Glass',
    image18: 'In the bathroom',
    image19: 'Only in dreams',
    material: 'Oil on paper',
    material2: 'Oil on canvas',
}

module.exports.fr = {
    expoDescription: fs.readFileSync('./src/copies/partials/expoAliciaAyaneguiDescriptionEn.txt').toString('utf-8'),
    username: 'Nom',
    message: 'Message',
    startMessage: 'Bienvenue sur le chat. Pendant la diffusion en direct, vous pouvez demander ou commenter tout ce que vous voulez à l\'artiste ou aux membres du Pared.',
    image1: 'Piliers',
    image2: 'Poids jaune',
    image3: 'Blancs',
    image4: 'Ruban blau',
    image5: 'Ombre rouge',
    image6: 'Reflet',
    image7: 'Paysage',
    image8: 'Froid',
    image9: 'Glace',
    image10: 'Fine brume',
    image11: 'Un',
    image12: 'Fumée',
    image13: 'Quelque chose par terre (diptyque)',
    image14: 'Disparitions (diptyque)',
    image15: 'Boueux',
    image16: 'Humidité',
    image17: 'Verre',
    image18: 'Dans la salle de bain',
    image19: 'Seulment dans les rêves',
    material: 'Huile sur papier',
    material2: 'Huile sur toile',
}
